# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-01 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_stats_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='upload_time',
            field=models.DateField(default=datetime.datetime(2017, 3, 1, 18, 25, 47, 246435)),
        ),
    ]
