# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-01 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170301_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='upload_time',
            field=models.DateField(default=datetime.datetime(2017, 3, 1, 18, 28, 50, 428398)),
        ),
    ]
