# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20170302_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
