# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20170302_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('s_count', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': '统计信息', 'verbose_name_plural': '统计信息'},
        ),
        migrations.AlterField(
            model_name='stats',
            name='cards',
            field=models.IntegerField(verbose_name='学习卡片数'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='是否达标'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='thetime',
            field=models.IntegerField(verbose_name='学习时间'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='注册用户'),
        ),
    ]
